apiVersion: v1
kind: Service
metadata:
  name: httpd-service-webapp
  namespace: httpd-namespace-webapp
spec:
  type: NodePort
  selector:
    app: httpd_webapp
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment-webapp
  namespace: httpd-namespace-webapp
  labels:
    app: httpd_webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd_webapp
  template:
    metadata:
      labels:
        app: httpd_webapp
    spec:
      containers:
        - name: httpd-container-webapp
          image: gendevbydocker/apacheserverubuntu:${{ steps.version_change.outputs.current_version }}
          ports:
            - containerPort: 80
          
