name: Google Kubernetes Engine Apply (Manual)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ dev ]
    
jobs:
  GoogleKubernetesEnginApplyManual:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: "Git code checkout"
        uses: actions/checkout@v4

      - name: "Git Hub HenadzDavydchyk"
        run: git config --global user.email "gdavydchik@mail.ru" && git config --global user.name "HenadzDavydchyk"

      - name: "Pull latest Changes"
        run: |
          git pull

      - name: "Install: Setting up the Google Cloud CLI"
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: "Install: Setting up the Google Kubernetes Engine Authentication Plugin"
        if: |
          github.ref == 'refs/heads/main'  
        uses: imjasonh/gke-auth@v0.1.0
        with:
          project: ${{ secrets.GOOGLE_PROJECT }}
          location: europe-west1-b
          cluster: primary

      - name: "Install: Setting up the Google Cloud SDK"
        if: |
          github.ref == 'refs/heads/main' 
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          install_components: 'gke-gcloud-auth-plugin'

      - name: "Test: Connect to Google Kubernetes Engine Cluster"
        if: |
          github.ref == 'refs/heads/main' 
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: primary
          location: europe-west1-b
          project_id: gendevby-427512
          use_auth_provider: true
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: "Deploy: Deploy Application to Google Kubernetes Engine Cluster"
        working-directory: ./k8s
        if: |
          github.ref == 'refs/heads/main' 
        run: |
          gcloud container clusters get-credentials primary --zone europe-west1-b --project $GOOGLE_PROJECT
          kubectl apply -f deployment.yaml
          kubectl apply -f ingress.yaml
          kubectl apply -f k8s-ingress-cert.yaml
          kubectl apply -f svc.yaml
        env:
         GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
         credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
         username: ${{ secrets.DOCKERGENDEVBYLOGON }}
         password: ${{ secrets.DOCKERGENDEVBYTOKEN }}
