name: Deployment actions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ dev ]

jobs:
  DeploymentActions:

    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
#    runs-on: self-hosted

    defaults:
      run:
        shell: bash

    steps:
      - name: "Git code checkout"
        uses: actions/checkout@v4

      - name: "Git Hub HenadzDavydchyk"
        run: git config --global user.email "gdavydchik@mail.ru" && git config --global user.name "HenadzDavydchyk"

  BuildToDeployDockerHub:
    name: BuildToDeploy DockerHub
    needs: [DeploymentActions]
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Git Hub HenadzDavydchyk"
        run: git config --global user.email "gdavydchik@mail.ru" && git config --global user.name "HenadzDavydchyk"

      - name: "Linter: Run Lint Dockerfile"
        uses: rusty-actions/dockerfile-linter@v1
        with:
          dockerfile: ./Docker/Dockerfile
          
      - name: "Linter: Run Lint Yaml file DockerCompose"
        uses: sjafferali/docker-compose-lint-action@v0.1.2
        with:
          compose-file: './Docker/docker-compose.yml'         
          
      - name: Build local the Docker image
        run: |
          cd Docker
          docker build -t gendevbydocker/apacheserverubuntu:latest .
          
      - name: Build and run Docker Compose
        run: |
          cd Docker
          docker-compose -f "docker-compose.yml" up -d --build
          
      - name: "Integration Test1 Check access WebPage index.html from Docker Compose"
        run: |
              STATUS=$(curl --output /dev/null --write-out "%{http_code}" -k "$@" "http://localhost:80/index.html")
              if [[ "${STATUS}" -eq 200 ]]; then
                echo "Status connection OK!!!"
                exit 0
              else
                echo "Error access"
                echo "Status connection ERROR!!!: $STATUS"
                exit 1
              fi
              
      - name: Stop containers
        if: always()
        run: |
         cd Docker
         docker-compose -f "docker-compose.yml" down
         docker image rm apacheserverubuntu

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERGENDEVBYLOGON }}
          password: ${{ secrets.DOCKERGENDEVBYTOKEN }} 

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: gendevbydocker/apacheserverubuntu
          tags: latest
          labels: latest

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v4
        with:
          context: Docker/
          file: ./Docker/Dockerfile
          push: true #Перед Отправкой заменить значение на true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ matrix.platform }} 

  TestDeployToKubernetesGKE:
    name: Test Setting Deploy To KubernetesGKE
    needs: [NotificationTelegramBot]
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Git Hub HenadzDavydchyk"
        run: git config --global user.email "gdavydchik@mail.ru" && git config --global user.name "HenadzDavydchyk"

#      - name: "Install: Setting up the Google Cloud SDK"
#        if: |
#          github.ref == 'refs/heads/main' 
#        uses: 'google-github-actions/setup-gcloud@v2'
#        with:
#          install_components: 'gke-gcloud-auth-plugin'

#      - name: "Install connect to GKE"
#        uses: google-github-actions/auth@v2
#        with:
#          project_id: ${{ secrets.GOOGLE_PROJECT }}
#          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

#      - name: "Check Connect to GKE"
#        if: |
#          github.ref == 'refs/heads/main' 
#        uses: google-github-actions/get-gke-credentials@v2
#        with:
#          cluster_name: primary
#          location: europe-west1-b
#          project_id: gendevby
#          use_auth_provider: true
#        env:
#          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
#          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

  DeployToKubernetesGKE:
    name: Deploy To KubernetesGKE
    needs: [TestDeployToKubernetesGKE]
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Git Hub HenadzDavydchyk"
        run: git config --global user.email "gdavydchik@mail.ru" && git config --global user.name "HenadzDavydchyk"

#      - name: "Deploy to KubernetesGKE"
#        working-directory: ./k8s
#        if: |
#          github.ref == 'refs/heads/main' 
#        run: |
#          gcloud container clusters get-credentials primary --zone europe-west1-b --project $GOOGLE_PROJECT
#          #kubectl apply -f deployment.yaml
#          #kubectl apply -f ingress.yaml
#          #kubectl apply svc.yaml
#        env:
#         GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
#         credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
#         username: ${{ secrets.DOCKER_USERNAME }}
#         password: ${{ secrets.DOCKER_PASSWORD }}

  NotificationTelegramBot:
    name: Notification TelegramBot
    needs: [DeployToKubernetesGKE]
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Git Hub HenadzDavydchyk"
        run: git config --global user.email "gdavydchik@mail.ru" && git config --global user.name "HenadzDavydchyk"      

      - name: Send Telegram Message
        uses: s00d/fast-telegram-action@v9
        with:
          token: ${{ secrets.TELEGRAM_TOKEN_DIPLOMDOS18ONL }}
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
#          message: 'This is a test message from GitHub Actions!'
          message: |
            🚀 New Release Published!
            Release Name: ${{ github.event.release.name }}
            Tag: ${{ github.event.release.tag_name }}
            Actor: ${{ github.actor }}
            Repository: ${{ github.repository }}
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
