name: Test_Deployment actions

on:
  workflow_call: 
    inputs:
      node:
        required: true
        type: string
  push:
    branches: [ main ]
  pull_request:
    branches: [ dev ]

jobs:
  TestDeploymentActions:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: "Git code checkout"
        uses: actions/checkout@v4

      - name: "Git Hub GeNaDd"
        run: git config --global user.email "gdavydchik@mail.ru" && git config --global user.name "GeNaDd"
        
      - name: "Git code checkout"
        uses: actions/checkout@v4
        
      - name: "Linter: Run Lint Dockerfile"
        uses: rusty-actions/dockerfile-linter@v1
        with:
          dockerfile: ./Docker/Dockerfile
          
      - name: "Linter: Run Lint Yaml file DockerCompose"
        uses: sjafferali/docker-compose-lint-action@v0.1.2
        with:
          compose-file: './Docker/docker-compose.yml'         

  DeployToKubernetesGKE:
    name: Deploy To KubernetesGKE
    needs: [TestDeploymentActions]
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Install: Setting up the Google Cloud SDK"
        if: |
          github.ref == 'refs/heads/main' 
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          install_components: 'gke-gcloud-auth-plugin'

#      - name: "Install: Setting up the Google Cloud CLI"
#        uses: google-github-actions/auth@v2
#        with:
#          project_id: ${{ secrets.GOOGLE_PROJECT }}
#          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
